Controllers/ExpensiveController.cs
using DespesasControlApp.DTOs;
using DespesasControlApp.Models;
using DespesasControlApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DespesasControlApp.Controllers
{
    public class DespesasController : Controller
    {
        private readonly ILogger<DespesasController> _logger;
        private readonly IDespesasService _DespesasService;

        public DespesasController(ILogger<DespesasController> logger,
            IDespesasService DespesasService)
        {
            _logger = logger;
            _DespesasService = DespesasService;
        }

        public async Task<IActionResult> Index()
        {
            var listDespesasDto = new ListDespesasDTO();

            listDespesasDto.Items = await _DespesasService.FindBy(listDespesasDto.StartDate, listDespesasDto.EndDate);

            return View(listDespesasDto);
        }

         public async Task<IActionResult> Republica()
        {
            var listDespesasDto = new ListDespesasDTO();

            listDespesasDto.Items = await _DespesasService.FindBy(listDespesasDto.StartDate, listDespesasDto.EndDate);

            return View(listDespesasDto);
        }

        [HttpPost]
        public async Task<IActionResult> Index(ListDespesasDTO listDespesasDto)
        {
            try
            {
                listDespesasDto.Items = await _DespesasService.FindBy(listDespesasDto.StartDate, listDespesasDto.EndDate);

                return View(listDespesasDto);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("CustomError", ex.Message);
                return View(listDespesasDto);
            }
        }

        public async Task<IActionResult> Create()
        {
            var createDespesasDto = new CreateDespesasDTO();

            return View(createDespesasDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDespesasDTO createDespesasDto)
        {
            try
            {
                await _DespesasService.Create(createDespesasDto);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("CustomError", ex.Message);
                return View(createDespesasDto);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Despesas/Create.cshtml
@model DespesasControlApp.DTOs.CreateDespesasDTO

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Description" placeholder="Digite a descrição" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Date" type="date" placeholder="Digite a data" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Value" type="number" placeholder="Digite o valor" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <a asp-action="Index" class="btn btn-secondary btn-login text-uppercase fw-bold">Voltar</a>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <button type="submit" class="btn btn-primary btn-login text-uppercase fw-bold">Criar</button>
            </div>
        </div>
    </div>
</form>

Views/Despesas/Index.cshtml
@model DespesasControlApp.DTOs.ListDespesasDTO

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm">
        <h1>Despesas</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <a asp-action="Create" asp-controller="Despesas" class="btn btn-primary btn-lg btn-block">Nova despesa</a>
    </div>
</div>


<div class="row">
    <div class="col-md">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descrição</th>
                    <th>Data de vencimento</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Items.Count > 0)
                {
                    foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Description</td>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@(item.Value / 5)</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="4">Nenhum registro encontrado.</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Despesas/Republica.cshtml
@model DespesasControlApp.DTOs.ListDespesasDTO

<div class="text-left">
    <h1 class="display-8">República</h1>
</div>
<h5>Gastos Totais</h5>

<div class="row">
    <div class="col=md">
        <table class="table">
            <tbody>
                @if(Model.Items.Count > 0)
                {
                    foreach(var item in Model.Items)
                    {

                        
                        <tr class="oi">
                            <td>@item.Description</td>
                            <td>R$ @item.Value</td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="4">Nenhum registro encontrado.</td></tr>
                }
            </tbody>
        </table>
    </div>
</div>



<style>
    .row {
       
    }

    table {
        border-collapse: separate;
        border-spacing: 0 8px;
        margin-top: -8px;
    }

    td {
        border: 1px solid #fad77b;
        border-left-width: 0;
        min-width: 120px;
        height: 18px;
        color: gray;
        font-size: 17px;

    }

        td:first-child {
            border-left-width: 1px;
        }

        tbody{
        background-color: #fad77b;
    }



</style>